#! /bin/sh
#
# Shows various status icons, listed below

source $(dirname $0)/panel_config
#    sdd() {
#        sdd=$(df -h /dev/sda2 | awk 'FNR == 2{print $3}')
#        echo "%{B$BG}%{F$CYAN} %{B-}%{F-}%{F$CYAN} ${sdd}"
#    }
#
#     hdd() {
#        hdd=$(df -h /dev/sda3 | awk 'FNR == 2{print $3}')
#        echo "%{B$BG}%{F$BLACK} %{B-}%{F-}%{F$BLACK} ${hdd}"
#    }
#
    mem() {
        mem=$(free -h | grep Mem: | awk '{print $3}')
        echo "%{B$BG}%{F$MAGENTA} %{B-}%{F-}%{F$MAGENTA} ${mem}"
    }
    
    batt() {
        battstate=` acpi | awk '{print $3}'`
        batticon=""
        batt=$(acpi | cut -d ',' -f 2 | awk '{key=$0; getline; print key "" $0;}' | cut -d ' ' -f 2 | cut -d '%' -f 1)
        if [ $battstate = "Discharging," ];
            then
            batticon=""
            if [ $batt -le 50 ]; then
                batticon=""
            fi
            if [ $batt -le 20 ]; then
                batticon=""
            fi
            if [ $batt -le 10 ]; then
                batticon=""
            fi
        elif [ $battstate = "Charging," ]; then
            batticon=""
        else
            batticon=""
        fi

        echo "%{B$BG}%{F$GREEN} $batticon%{B-}%{F-}%{F$GREEN} ${batt}%"
    }

    clock() {
        clock=$(date "+%a, %d %b %H:%M")
        echo "%{B$BG}%{F$BLUE} %{B-}%{F-}%{F$BLUE} ${clock}"
    }

    vol() {
        vol=$(amixer get Master | sed -nr '$ s:.*\[(.+%)].*:\1:p' | tr -d "%")
        volicon=""
        mute=$(amixer get Master | awk 'FNR==5 {print $6}')
        if [ $vol -gt 0 ]; then
            volicon=""
        fi
        if [ $vol -gt 50 ]; then
            volicon=""
        fi
        if [ $vol -gt 75 ]; then
            volicon=""
        fi
        vol="${vol}%"
        if [ "$mute" = "[off]" ]; then
            vol="mute";
            volicon="";
        fi
        echo "%{B$BG}%{F$YELLOW} $volicon%{B-}%{F-}%{F$YELLOW} ${vol}"
     } 

    while :; do
        printf "%s\n" "S$(mem) $(batt) $(vol) $(clock) "
        sleep 0.5
    done

