#! /bin/sh
#
# Script to start lemonbar (second panel)

source $(dirname $0)/panel_config
source $(dirname $0)/profile2
if [ $(pgrep -cx bspwm_panel.sh) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &

xtitle -sf 'T%s\n' > "$PANEL_FIFO" &

sh ~/.config/bspwm/panel/panel_status_pacman > "$PANEL_FIFO" &
sh ~/.config/bspwm/panel/panel_status  > "$PANEL_FIFO" &

panel_bar < "$PANEL_FIFO" \
     | lemonbar -p \
           -g "$geometry2" \
           -f "$FONT1" -f "$FONT2" -f "$FONT3"\
           -B "$BAR_BG" \
           -F "$BAR_FG" \
           | while read line; do eval "$line"; done &
wait

