#! /bin/sh
#
# config file for bspwm 

### bspc config ###

bspc config border_width        0
bspc config window_gap          10
bspc config top_padding         26
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config normal_border_color "#332d38"
bspc config active_border_color "#938e8f"
bspc config focused_border_color "#6f6b75"

### rename window manager for compatibility ###

wmname LG3D

### detect second monitor and output to it ###

hdmi1isconnected="`xrandr -q | awk '/HDMI1 connected/'`"
if [ "$hdmi1isconnected" != "" ]; then
    xrandr --output HDMI1 --auto --left-of LVDS1
    bspc monitor LVDS1 -d ◆ ◆ ◆ ◆ ◆ 
    bspc monitor HDMI1 -d ◆ ◆ ◆ ◆ ◆
else
bspc monitor -d  ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆
fi

### bspc program rules ###

bspc rule -a Gimp state=floating follow=on
bspc rule -a mpv desktop=^0

### programs to run upon starting ### 

# lemonbar
panel &
#if [ "$hdmi1isconnected" != "" ]; then
#    panel2 &
#fi
#stalonetray
sleep 3 && stalonetray -c ~/.config/.stalonetrayrc &
# network manager applet
dbus-launch nm-applet &
# battery notification script
sh ~/scripts/battery_monitor.sh &
# linux feed reader
liferea &

