#! /bin/sh

bspc config border_width        0
bspc config window_gap          10

bspc config top_padding 26

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#5f6774"
bspc config active_border_color "#799286"
bspc config focused_border_color "#7d4b4f"
bspc config presel_border_color "#b55f20"
bspc config urgent_border_color "#BE3D0B"
bspc config focused_locked_border_color "#b55f20"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1s

bspc monitor -d ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆

bspc rule -a Gimp follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


panel &
sleep 1 && stalonetray -c ~/.config/.stalonetrayrc &
nm-applet &
sh ~/scripts/battery_monitor.sh &
