#! /bin/sh
#
# bar input parser for bspwm 

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/panel_config

while read -r line ; do
    case $line in
        P*)
            pacman="${line#?}"
            ;;
        S*)
            sys_infos="${line#?}"
            ;;
        T*)
            # window title
            title=$(echo ${line#?} | sed 's^\(.\{40\}\).*^\1...^')
            title="%{F$TITLE_FG} ${title} ${LPAD} %{F-}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        # desktops
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                FG=$F_O_FG
                                #BG=$F_O_BG
                                ;;
                            F*)
                                # focused free desktop
                                FG=$F_F_FG
                                BG=$F_F_BG
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$F_U_FG
                                BG=$F_U_BG
                                ;;
                            o*)# occupied desktop
                                FG=$O_FG
                                BG=$O_BG
                                ;;
                            f*)
                                # free desktop
                                FG=$F_FG
                                BG=$F_BG
                                ;;
                            u*)
                                # urgent desktop
                                FG=$U_FG
                                BG=$U_BG
                                ;;
                        esac
                        wm_infos="${wm_infos}%{F$FG B$BG A:bspc desktop -f ${name}:}${PAD}${name}${PAD}%{A B- F-}"

                        mus() {
                            mus=$(mpc current)
                            if [[ $mus ]]; then
                                echo "%{B$BG}%{F$RED}  %{B-}%{F-}%{F$TEXTCOLOR} ${mus}"
                            else
                            echo
                            fi
                            return 
                        }
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac

    printf "%s\n" "%{l}$wm_infos $(mus) %{c}$title %{r}$pacman $sys_infos "
done


