#!/bin/sh

source $(dirname $0)/config

(echo " $@"; sleep $DURATION)\
| lemonbar \
        -f "$FONT1","$FONT2"\
        -F "$BAR_FG"\
        -B "$BAR_FG"\
        -g "$NOTIFY_GEOMETRY"\
        -u $LINEHEIGHT
