#! /bin/sh

bspc config border_width        0
bspc config window_gap          10

bspc config top_padding 26

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#332d38"
bspc config active_border_color "#938e8f"
bspc config focused_border_color "#6f6b75"
bspc config presel_border_color "#bf6257"
bspc config urgent_border_color "#BE3D0B"
bspc config focused_locked_border_color "#825969"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1s

wmname LG3D

hdmi1isconnected="`xrandr -q | awk '/HDMI1 connected/'`"
if [ "$hdmi1isconnected" != "" ]; then
    xrandr --output HDMI1 --left-of LVDS1
    bspc monitor LVDS1 -d ◆ ◆ ◆ ◆ ◆ 
    bspc monitor HDMI1 -d ◆ ◆ ◆ ◆ ◆
else
    bspc monitor -d  ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆ ◆
fi

bspc rule -a Gimp follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


panel &
if [ "$hdmi1isconnected" != "" ]; then
    panel2 &
fi
sleep 1 && stalonetray -c ~/.config/.stalonetrayrc &
nm-applet &
sh ~/scripts/battery_monitor.sh &
